# This is a basic workflow to help you get started with Actions

name: BugBountyScan

on:
  push:
    branches:
      - master

jobs:
  detect_tests:
    runs-on: ubuntu-latest
    name: A workflow to test the work of DataSecure
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: CodeAnalysis
      uses: bugbounty-site/GitSecure@master
      with:
        slack_hook: ${{ secrets.slack_webhook }}
        
    - name: Git leaks Scan
      run: |
        sudo docker run --rm --name=gitleaks zricethezav/gitleaks -v -r https://github.com/FrancisBilla/chess-workflow.git --pretty     
     
